"""Exercise the exported service without installing or starting systemd.

COMMUNITY_EXPORT points to an export generated by packaging/community/export.py.
"""
import importlib.util
import json
import os
from pathlib import Path
import pwd
import shutil
import sys
import tempfile
import threading
import unittest
from types import SimpleNamespace
from unittest.mock import patch

EXPORT = Path(os.environ['COMMUNITY_EXPORT'])
SERVICE = EXPORT / 'omarchy-screen-time/service'
sys.path.insert(0, str(SERVICE))
from omarchy_kids.core import paths, proto, session
from omarchy_kids.core.auth import ParentAuth
from omarchy_kids.core.credentials import password_record, matches
from omarchy_kids.core.daemon import Daemon
from omarchy_kids.core.storage import write_json, read_json, public_status


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


manager = load('controls_manager', SERVICE / 'manage.py')
desktop = load('school_desktop', SERVICE / 'school-desktop.py')
handoff = load('math_handoff', EXPORT / 'omarchy-screen-time/math-handoff.py')


class ControlsTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix='community-controls-')
        self.addCleanup(temporary.cleanup)
        self.base = Path(temporary.name)
        env = patch.dict(os.environ, {'SCREEN_TIME_ROOT': str(self.base), 'SCREEN_TIME_LOCK_COMMAND': '/usr/bin/true'})
        env.start(); self.addCleanup(env.stop)
        self.uid = os.getuid()
        self.user = pwd.getpwuid(self.uid).pw_name
        write_json(self.base / 'config.json', {'version': 3, 'profiles': {'default': {}}, 'users': {}})
        self.host = Daemon(paths.detect(), log=lambda _: None)
        self.host.auth = ParentAuth(verifier=lambda user, password: password == 'correct password')
        mock = patch.object(session.SessionWatcher, 'poll', lambda watcher: watcher)
        mock.start(); self.addCleanup(mock.stop)

    def send(self, scope, command, root=False, **values):
        return self.host.dispatch(0 if root else self.uid, {'scope': scope, 'cmd': command, 'user': self.user, **values})

    def enable(self, scope):
        self.assertTrue(self.send(scope, 'users.set', root=True, enabled=True)['ok'])

    def test_modules_enroll_and_remove_independently(self):
        self.enable('school')
        self.assertEqual(self.send('time', 'status')['error'], 'not_managed')
        self.assertTrue(self.send('school', 'mode.set', mode='school')['ok'])
        self.assertEqual(self.send('school', 'mode.set', mode='free')['error'], 'parent_required')
        self.enable('time')
        self.assertTrue(self.send('time', 'users.set', root=True, enabled=False)['ok'])
        self.assertEqual(self.send('school', 'mode.get')['mode'], 'school')
        self.enable('time')
        self.assertTrue(self.send('school', 'users.set', root=True, enabled=False)['ok'])
        self.assertTrue(self.send('time', 'status')['ok'])

    def test_password_check_cannot_select_another_user_or_settings_scope(self):
        self.enable('school'); self.enable('time')
        self.assertEqual(self.send('school', 'mode.set', mode='free', password='bad')['error'], 'bad_password')
        self.assertTrue(self.send('school', 'mode.set', mode='free', password='correct password')['ok'])
        self.assertEqual(self.host.resolve_uid(self.uid, {'user': 'root'}), self.uid)
        self.assertEqual(self.send('school', 'config.patch', root=True, patch={'budget_minutes': {'mon': 0}})['error'], 'bad_patch')
        self.assertEqual(self.send('time', 'config.patch', root=True, patch={'school_apps': ['chromium'], 'earn': {}})['error'], 'mixed_module_patch')

    def test_slow_password_check_does_not_block_clock_and_parallel_guesses(self):
        self.enable('school'); self.enable('time')
        started, finish = threading.Event(), threading.Event()
        def verify(*_):
            started.set(); finish.wait(2); return True
        self.host.auth = ParentAuth(verifier=verify)
        thread = threading.Thread(target=lambda: self.send('school', 'mode.set', mode='free', password='correct password'))
        thread.start()
        try:
            self.assertTrue(started.wait(1))
            self.assertTrue(self.host.lock.acquire(timeout=0.1)); self.host.lock.release()
            self.assertTrue(self.send('time', 'status')['ok'])
            self.assertEqual(self.send('school', 'mode.set', mode='free', password='correct password')['error'], 'password_checking')
        finally:
            finish.set(); thread.join(3)

    def test_password_hash_and_shared_lockout(self):
        record = password_record('a long private password')
        self.assertTrue(matches('a long private password', record))
        self.assertFalse(matches('wrong password', record))
        self.assertFalse(matches('anything', {}))
        with self.assertRaises(ValueError): password_record('short')
        self.enable('school'); self.enable('time')
        for scope in ('school', 'time'):
            self.assertEqual(self.send(scope, 'config.get', password='bad')['error'], 'bad_password')
        self.assertEqual(self.send('school', 'config.get', password='correct password')['error'], 'password_locked_out')

    def test_math_reward_is_checked_once_by_service(self):
        self.enable('time')
        reply = self.send('time', 'quiz.next', choices=6, level='grade1', reward_seconds=999999)
        self.assertEqual(reply['level'], 'grade5')
        pending = self.host.services['time'].account_for(self.uid).quiz.pending
        self.assertIn(pending.answer, reply['question']['choices'])
        self.assertNotIn('answer', reply['question'])
        pending.issued_at -= 3
        result = self.send('time', 'quiz.answer', id=reply['question']['id'], answer=pending.answer)
        self.assertTrue(result['correct'])
        self.assertLess(result['reward_seconds'], 999999)
        self.assertEqual(self.send('time', 'quiz.answer', id=reply['question']['id'], answer=pending.answer)['error'], 'no_such_question')

    def test_no_os_authentication_or_demo_password_bypass(self):
        auth = ParentAuth(verifier=lambda *_: False)
        self.assertEqual(auth.check(self.uid, {'password': '1234'}, demo=True)['error'], 'bad_password')
        text = (SERVICE / 'omarchy_kids/core/auth.py').read_text()
        self.assertNotIn('/usr/bin/sudo', text)
        self.assertNotIn('SCREEN_TIME_TEST_PASSWORD', text)

    def test_oversize_protocol_line_is_rejected_with_newline(self):
        sock = SimpleNamespace(recv=lambda _: b'"' + b'x' * proto.MAX_LINE + b'"\n')
        with self.assertRaises(proto.ProtocolError): proto.LineReader(sock).read()

    def test_public_status_is_readable_under_private_service_umask(self):
        layout = paths.Layout('system', self.base / 'config.json', self.base / 'private', self.base / 'sock')
        with patch.dict(os.environ, {}, clear=True), patch.object(paths, 'PARENT_STATE_DIR', self.base / 'public'):
            mask = os.umask(0o077)
            try: public_status(layout, 'screen-time', 'school-mode', {'schemaVersion': 1, 'enabled': False})
            finally: os.umask(mask)
            target = self.base / 'public/screen-time/school-mode/status.json'
            self.assertEqual(target.stat().st_mode & 0o777, 0o644)
            for directory in [target.parent, target.parent.parent, self.base / 'public']:
                self.assertEqual(directory.stat().st_mode & 0o777, 0o755)

    def test_handoff_never_resets_an_open_math_quiz_or_runs_while_locked(self):
        for outputs, expected_calls in [(['true'], 1), (['false', 'true'], 2), (['false', 'false', 'true'], 3), (['false', 'false', 'false', 'ok'], 4)]:
            with patch.object(handoff, 'should_open', return_value=True), patch.object(handoff, 'reply', side_effect=outputs) as reply:
                handoff.main()
                self.assertEqual(reply.call_count, expected_calls)


class InstallerTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix='community-install-')
        self.addCleanup(temporary.cleanup)
        self.base = Path(temporary.name)
        replacements = {'PREFIX': self.base / 'usr/lib/controls', 'CONFIG': self.base / 'etc/controls',
                        'STATE': self.base / 'var/lib/controls', 'UNIT': self.base / 'etc/systemd/system/omarchy-kids-controls.service',
                        'MARKER': self.base / 'etc/controls/installation.json', 'PASSWORD_PATH': self.base / 'etc/controls/password.json'}
        for name, value in replacements.items():
            mock = patch.object(manager, name, value); mock.start(); self.addCleanup(mock.stop)
        manager.PREFIX.parent.mkdir(parents=True)
        manager.UNIT.parent.mkdir(parents=True)
        self.wrapper = self.base / 'usr/bin/omarchy-kids-controls'
        self.wrapper.parent.mkdir(parents=True)
        mock = patch.object(manager, 'wrappers', return_value={self.wrapper: '#!/bin/bash\ntrue\n'})
        mock.start(); self.addCleanup(mock.stop)
        manager.CONFIG.mkdir(parents=True)
        write_json(manager.PASSWORD_PATH, {'test': True})

    def install(self, module, upgrade=False):
        original_is_file = Path.is_file
        def is_file(path):
            return str(path) == '/usr/share/omarchy/config/omarchy/shell.json' or original_is_file(path)
        with patch.object(manager, 'check_account'), patch.object(Path, 'is_file', is_file), \
             patch.object(manager, 'run'), patch.object(manager, 'wait_for_service'), patch.object(manager, 'enroll') as enroll:
            manager.install(SimpleNamespace(user='linnea', module=module, upgrade=upgrade))
            return enroll.call_args_list

    def test_install_remove_preserves_other_module_and_data(self):
        self.install('time'); self.install('school')
        self.assertEqual(manager.installed()['modules'], ['school', 'time'])
        write_json(manager.config_path('time'), {'users': {'linnea': {}}})
        with patch.object(manager, 'enroll') as enroll, patch.object(manager, 'restore_desktop'), patch.object(manager, 'run'):
            manager.remove('time')
            enroll.assert_called_once_with('time', 'linnea', False)
            self.assertTrue(manager.PREFIX.is_dir())
            self.assertEqual(manager.installed()['modules'], ['school'])
            manager.remove('school')
        self.assertFalse(manager.PREFIX.exists())
        self.assertFalse(self.wrapper.exists())
        self.assertFalse(manager.UNIT.exists())
        self.assertTrue(manager.PASSWORD_PATH.exists())
        self.assertTrue(manager.config_path('time').exists())

    def test_fresh_combined_install_enrolls_both_controls(self):
        calls = self.install('controls')
        self.assertEqual([call.args for call in calls], [('school', 'linnea', True), ('time', 'linnea', True)])
        self.assertEqual(manager.installed()['modules'], ['school', 'time'])

    def test_combined_upgrade_preserves_existing_enrollments_and_settings(self):
        self.install('school')
        school = {'users': {'linnea': {'profile': 'default'}}, 'profiles': {'default': {'school_apps': ['chromium']}}}
        time = {'users': {}, 'profiles': {'default': {'budget_minutes': {'mon': 35}}}}
        write_json(manager.config_path('school'), school)
        write_json(manager.config_path('time'), time)
        calls = self.install('controls', upgrade=True)
        self.assertEqual(calls, [])
        self.assertEqual(read_json(manager.config_path('school'), {}), school)
        self.assertEqual(read_json(manager.config_path('time'), {}), time)
        self.assertEqual(manager.installed()['modules'], ['school', 'time'])

    def test_command_collision_is_not_overwritten(self):
        self.wrapper.write_text('another application')
        with self.assertRaisesRegex(ValueError, 'collision'): self.install('time')
        self.assertEqual(self.wrapper.read_text(), 'another application')

    def test_local_service_edits_are_preserved(self):
        self.install('time')
        (manager.PREFIX / 'runtime.py').write_text('local change')
        with self.assertRaisesRegex(ValueError, 'local edits'): self.install('school')
        self.assertEqual((manager.PREFIX / 'runtime.py').read_text(), 'local change')

    def test_dangling_service_symlink_is_not_followed(self):
        manager.UNIT.symlink_to(self.base / 'unrelated')
        with self.assertRaisesRegex(ValueError, 'collision'): self.install('time')
        self.assertTrue(manager.UNIT.is_symlink())


class DesktopTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(prefix='community-desktop-')
        self.addCleanup(temporary.cleanup)
        base = Path(temporary.name)
        for name, value in {'STATE': base, 'CONFIG': base / 'shell.json', 'JOURNAL': base / 'desktop.json'}.items():
            mock = patch.object(desktop, name, value); mock.start(); self.addCleanup(mock.stop)
        desktop.write(desktop.CONFIG, {'bar': {'layout': {'right': ['my.widget']}}, 'disabledPlugins': ['my.disabled']})

    def test_desktop_restores_only_its_own_change(self):
        with patch.object(desktop, 'command', return_value='off'):
            desktop.enter({})
            config = desktop.read(desktop.CONFIG)
            self.assertIn('omarchy.menu', config['disabledPlugins'])
            config['newUserSetting'] = 42
            desktop.write(desktop.CONFIG, config)
            desktop.restore(desktop.read(desktop.JOURNAL))
        self.assertEqual(desktop.read(desktop.CONFIG), {'bar': {'layout': {'right': ['my.widget']}}, 'disabledPlugins': ['my.disabled'], 'newUserSetting': 42})
        self.assertFalse(desktop.JOURNAL.exists())

    def test_previously_disabled_menu_stays_disabled(self):
        desktop.menu(True)
        with patch.object(desktop, 'command', return_value='on'):
            desktop.enter({}); desktop.restore(desktop.read(desktop.JOURNAL))
        self.assertIn('omarchy.menu', desktop.read(desktop.CONFIG)['disabledPlugins'])

    def test_new_compositor_session_reapplies_shortcuts_and_parking(self):
        with patch.object(desktop, 'command', return_value='off') as command:
            with patch.dict(os.environ, {'HYPRLAND_INSTANCE_SIGNATURE': 'session-one'}): desktop.enter({})
            command.reset_mock()
            with patch.dict(os.environ, {'HYPRLAND_INSTANCE_SIGNATURE': 'session-two'}): desktop.enter(desktop.read(desktop.JOURNAL))
            self.assertTrue(any(call.args[-2:] == (str(desktop.SOURCE / 'shortcut-policy'), 'enter') for call in command.call_args_list))
            self.assertEqual(desktop.read(desktop.JOURNAL)['instance'], 'session-two')

    def test_failed_restore_keeps_recovery_journal(self):
        with patch.object(desktop, 'command', return_value='off'): desktop.enter({})
        with patch.object(desktop, 'command', side_effect=ValueError('IPC unavailable')):
            with self.assertRaises(ValueError): desktop.restore(desktop.read(desktop.JOURNAL))
        self.assertTrue(desktop.JOURNAL.exists())

    def test_invalid_or_symlink_configuration_is_never_replaced(self):
        desktop.CONFIG.write_text('invalid json')
        with self.assertRaises(ValueError): desktop.menu(True)
        self.assertEqual(desktop.CONFIG.read_text(), 'invalid json')
        desktop.CONFIG.unlink(); desktop.CONFIG.symlink_to(desktop.STATE / 'elsewhere')
        with self.assertRaises(ValueError): desktop.write(desktop.CONFIG, {})


if __name__ == '__main__':
    unittest.main()
