"""Serialized writes to files shared by parent features."""
import argparse
import json
import re
from pathlib import Path
from .storage import locked, read_json, write_json
from .paths import write_private


def config_change(path, key=None, value=None, comments=(), only_if_missing=False):
    path = Path(path)
    if key is not None and not re.fullmatch(r'[a-z][a-z0-9_]*', key):
        raise ValueError('invalid configuration key')
    with locked(path.with_name('.' + path.name + '.lock')):
        text = path.read_text() if path.exists() else '# Omarchy kids mode parent settings. Each feature owns its own keys.\n'
        if key:
            pattern = re.compile(r'^\s*' + re.escape(key) + r'\s*=.*$', re.M)
            found = pattern.search(text)
            if only_if_missing and found:
                return
            line = key + '=' + value
            if found:
                text = pattern.sub(lambda _: line, text)
            else:
                text = text.rstrip() + '\n\n' + ''.join('# ' + c + '\n' for c in comments) + line + '\n'
        write_private(path, text)
        path.chmod(0o644)


def browser_change(path, module=None, fragment=None, reset_base=False):
    path = Path(path)
    ledger = path.with_name('.omarchy-parent-policies.json')
    with locked(path.with_name('.omarchy-parent-policies.lock')):
        document = read_json(path, {'policies': {}})
        policy = document.setdefault('policies', {})
        state = read_json(ledger, {'base': {}, 'contributions': {}})
        if reset_base:
            for key in state['base']:
                state['base'][key] = {'present': key in policy, 'value': policy.get(key)}
        if module:
            if module not in ('dns', 'browsing') or not isinstance(fragment, dict):
                raise ValueError('invalid policy contribution')
            for key in fragment:
                state['base'].setdefault(key, {'present': key in policy, 'value': policy.get(key)})
            if fragment:
                state['contributions'][module] = fragment
            else:
                state['contributions'].pop(module, None)
        for key, old in state['base'].items():
            if old['present']:
                policy[key] = old['value']
            else:
                policy.pop(key, None)
        for owner in sorted(state['contributions']):
            policy.update(state['contributions'][owner])
        # Persist ownership first; reapplying after interruption reproduces
        # the same final policy without dropping another module's keys.
        write_json(ledger, state)
        write_json(path, document)
        path.chmod(0o644)


def adopt_browser_policy(path, modules):
    """Record ownership of keys generated by the old bundled commands once."""
    path = Path(path)
    ledger = path.with_name('.omarchy-parent-policies.json')
    with locked(path.with_name('.omarchy-parent-policies.lock')):
        if ledger.exists() or not path.exists():
            return
        document = read_json(path)
        policies = document.get('policies', {})
        state = {'base': {}, 'contributions': {}}
        keys = {'dns': ('DNSOverHTTPS', 'WebsiteFilter'), 'browsing': ('DisablePrivateBrowsing',)}
        for module in modules:
            fragment = {key: policies[key] for key in keys[module] if key in policies}
            if fragment:
                state['contributions'][module] = fragment
                for key in fragment:
                    state['base'][key] = {'present': False, 'value': None}
        write_json(path.with_name(path.name + '.before-kids-modules'), document)
        write_json(ledger, state)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('kind', choices=['config', 'browser', 'browser-reapply', 'disable'])
    parser.add_argument('path')
    parser.add_argument('args', nargs='*')
    args = parser.parse_args()
    if args.kind == 'disable':
        username, status_path = args.args
        target = Path(args.path)
        with locked(target.with_name('.' + target.name + '.lock')):
            config = read_json(target, {})
            previous = config.setdefault('users', {}).pop(username, None)
            if previous is not None:
                config.setdefault('disabled_users', {})[username] = previous
            write_json(target, config)
            write_json(Path(status_path), {'schemaVersion': 1, 'enabled': False, 'mode': 'free'})
            Path(status_path).chmod(0o644)
    elif args.kind == 'browser-reapply':
        browser_change(args.path, reset_base=True)
    elif args.kind == 'browser':
        browser_change(args.path, args.args[0], json.loads(args.args[1]))
    else:
        operation, *values = args.args
        if operation == 'init':
            config_change(args.path)
        else:
            key, value, *comments = values
            config_change(args.path, key, value, comments, operation == 'document')
